//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "trade_outcome")]
pub enum TradeOutcome {
    #[sea_orm(string_value = "WIN")]
    Win,
    #[sea_orm(string_value = "LOSS")]
    Loss,
}
