//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_name: String,
    pub password: String,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::address::Entity")]
    Address,
    #[sea_orm(has_many = "super::broker_information::Entity")]
    BrokerInformation,
    #[sea_orm(has_many = "super::trade::Entity")]
    Trade,
    #[sea_orm(has_many = "super::user_information::Entity")]
    UserInformation,
}

impl Related<super::address::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Address.def()
    }
}

impl Related<super::broker_information::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BrokerInformation.def()
    }
}

impl Related<super::trade::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trade.def()
    }
}

impl Related<super::user_information::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserInformation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
