// @generated automatically by Diesel CLI.

pub mod external {
    /// A module containing custom SQL type definitions
    ///
    /// (Automatically generated by Diesel.)
    pub mod sql_types {
        /// The `external.broker` SQL type
        ///
        /// (Automatically generated by Diesel.)
        #[derive(diesel::sql_types::SqlType)]
        #[diesel(postgres_type(name = "broker", schema = "external"))]
        pub struct Broker;

        /// The `external.trade_action` SQL type
        ///
        /// (Automatically generated by Diesel.)
        #[derive(diesel::sql_types::SqlType)]
        #[diesel(postgres_type(name = "trade_action", schema = "external"))]
        pub struct TradeAction;

        /// The `external.trade_outcome` SQL type
        ///
        /// (Automatically generated by Diesel.)
        #[derive(diesel::sql_types::SqlType)]
        #[diesel(postgres_type(name = "trade_outcome", schema = "external"))]
        pub struct TradeOutcome;

        /// The `external.trade_type` SQL type
        ///
        /// (Automatically generated by Diesel.)
        #[derive(diesel::sql_types::SqlType)]
        #[diesel(postgres_type(name = "trade_type", schema = "external"))]
        pub struct TradeType;
    }

    diesel::table! {
        /// Representation of the `external.addresses` table.
        ///
        /// (Automatically generated by Diesel.)
        external.addresses (id) {
            /// The `id` column of the `external.addresses` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `street` column of the `external.addresses` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            street -> Varchar,
            /// The `city` column of the `external.addresses` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            city -> Varchar,
            /// The `zip_code` column of the `external.addresses` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            zip_code -> Varchar,
            /// The `user_id` column of the `external.addresses` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            user_id -> Uuid,
            /// The `created_at` column of the `external.addresses` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Nullable<Timestamptz>,
            /// The `updated_at` column of the `external.addresses` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Nullable<Timestamptz>,
        }
    }

    diesel::table! {
        /// Representation of the `external.broker_information` table.
        ///
        /// (Automatically generated by Diesel.)
        external.broker_information (id) {
            /// The `id` column of the `external.broker_information` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `po_ssid` column of the `external.broker_information` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 512]
            po_ssid -> Varchar,
            /// The `po_user_id` column of the `external.broker_information` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            po_user_id -> Int4,
            /// The `is_demo` column of the `external.broker_information` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            is_demo -> Bool,
            /// The `account_balance` column of the `external.broker_information` table.
            ///
            /// Its SQL type is `Numeric`.
            ///
            /// (Automatically generated by Diesel.)
            account_balance -> Numeric,
            /// The `user_id` column of the `external.broker_information` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            user_id -> Uuid,
            /// The `created_at` column of the `external.broker_information` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Nullable<Timestamptz>,
            /// The `updated_at` column of the `external.broker_information` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Nullable<Timestamptz>,
        }
    }

    diesel::table! {
        /// Representation of the `external.candles` table.
        ///
        /// (Automatically generated by Diesel.)
        external.candles (id) {
            /// The `id` column of the `external.candles` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `asset` column of the `external.candles` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 20]
            asset -> Varchar,
            /// The `open` column of the `external.candles` table.
            ///
            /// Its SQL type is `Float8`.
            ///
            /// (Automatically generated by Diesel.)
            open -> Float8,
            /// The `high` column of the `external.candles` table.
            ///
            /// Its SQL type is `Float8`.
            ///
            /// (Automatically generated by Diesel.)
            high -> Float8,
            /// The `low` column of the `external.candles` table.
            ///
            /// Its SQL type is `Float8`.
            ///
            /// (Automatically generated by Diesel.)
            low -> Float8,
            /// The `close` column of the `external.candles` table.
            ///
            /// Its SQL type is `Float8`.
            ///
            /// (Automatically generated by Diesel.)
            close -> Float8,
            /// The `timestamp` column of the `external.candles` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            timestamp -> Timestamptz,
            /// The `time_frame` column of the `external.candles` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            time_frame -> Int4,
            /// The `created_at` column of the `external.candles` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Nullable<Timestamptz>,
            /// The `updated_at` column of the `external.candles` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Nullable<Timestamptz>,
        }
    }

    diesel::table! {
        /// Representation of the `external.trade_session` table.
        ///
        /// (Automatically generated by Diesel.)
        external.trade_session (id) {
            /// The `id` column of the `external.trade_session` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `open_time` column of the `external.trade_session` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            open_time -> Timestamptz,
            /// The `close_time` column of the `external.trade_session` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            close_time -> Timestamptz,
            /// The `created_at` column of the `external.trade_session` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Nullable<Timestamptz>,
            /// The `updated_at` column of the `external.trade_session` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Nullable<Timestamptz>,
        }
    }

    diesel::table! {
        use diesel::sql_types::*;
        use super::sql_types::Broker;
        use super::sql_types::TradeAction;

        /// Representation of the `external.trade_signals` table.
        ///
        /// (Automatically generated by Diesel.)
        external.trade_signals (id) {
            /// The `id` column of the `external.trade_signals` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `asset` column of the `external.trade_signals` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 10]
            asset -> Varchar,
            /// The `entry_time` column of the `external.trade_signals` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            entry_time -> Timestamptz,
            /// The `expiry` column of the `external.trade_signals` table.
            ///
            /// Its SQL type is `Int4`.
            ///
            /// (Automatically generated by Diesel.)
            expiry -> Int4,
            /// The `broker` column of the `external.trade_signals` table.
            ///
            /// Its SQL type is `Broker`.
            ///
            /// (Automatically generated by Diesel.)
            broker -> Broker,
            /// The `action` column of the `external.trade_signals` table.
            ///
            /// Its SQL type is `TradeAction`.
            ///
            /// (Automatically generated by Diesel.)
            action -> TradeAction,
            /// The `created_at` column of the `external.trade_signals` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Nullable<Timestamptz>,
            /// The `updated_at` column of the `external.trade_signals` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Nullable<Timestamptz>,
        }
    }

    diesel::table! {
        use diesel::sql_types::*;
        use super::sql_types::TradeOutcome;
        use super::sql_types::TradeAction;
        use super::sql_types::TradeType;

        /// Representation of the `external.trades` table.
        ///
        /// (Automatically generated by Diesel.)
        external.trades (id) {
            /// The `id` column of the `external.trades` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `order_id` column of the `external.trades` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            order_id -> Uuid,
            /// The `asset` column of the `external.trades` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 10]
            asset -> Varchar,
            /// The `payout_rate` column of the `external.trades` table.
            ///
            /// Its SQL type is `Float8`.
            ///
            /// (Automatically generated by Diesel.)
            payout_rate -> Float8,
            /// The `entry_time` column of the `external.trades` table.
            ///
            /// Its SQL type is `Timestamptz`.
            ///
            /// (Automatically generated by Diesel.)
            entry_time -> Timestamptz,
            /// The `profit` column of the `external.trades` table.
            ///
            /// Its SQL type is `Numeric`.
            ///
            /// (Automatically generated by Diesel.)
            profit -> Numeric,
            /// The `stake_amount` column of the `external.trades` table.
            ///
            /// Its SQL type is `Numeric`.
            ///
            /// (Automatically generated by Diesel.)
            stake_amount -> Numeric,
            /// The `outcome` column of the `external.trades` table.
            ///
            /// Its SQL type is `Nullable<TradeOutcome>`.
            ///
            /// (Automatically generated by Diesel.)
            outcome -> Nullable<TradeOutcome>,
            /// The `action` column of the `external.trades` table.
            ///
            /// Its SQL type is `TradeAction`.
            ///
            /// (Automatically generated by Diesel.)
            action -> TradeAction,
            /// The `trade_type` column of the `external.trades` table.
            ///
            /// Its SQL type is `TradeType`.
            ///
            /// (Automatically generated by Diesel.)
            trade_type -> TradeType,
            /// The `user_id` column of the `external.trades` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            user_id -> Uuid,
            /// The `signal_id` column of the `external.trades` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            signal_id -> Uuid,
            /// The `mart_trade_id` column of the `external.trades` table.
            ///
            /// Its SQL type is `Nullable<Uuid>`.
            ///
            /// (Automatically generated by Diesel.)
            mart_trade_id -> Nullable<Uuid>,
            /// The `created_at` column of the `external.trades` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Nullable<Timestamptz>,
            /// The `updated_at` column of the `external.trades` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Nullable<Timestamptz>,
        }
    }

    diesel::table! {
        /// Representation of the `external.user_information` table.
        ///
        /// (Automatically generated by Diesel.)
        external.user_information (id) {
            /// The `id` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `first_name` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            first_name -> Varchar,
            /// The `last_name` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            last_name -> Varchar,
            /// The `middle_name` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Nullable<Varchar>`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            middle_name -> Nullable<Varchar>,
            /// The `gender` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            gender -> Varchar,
            /// The `phone_no` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 20]
            phone_no -> Varchar,
            /// The `email` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 128]
            email -> Varchar,
            /// The `date_of_birth` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Date`.
            ///
            /// (Automatically generated by Diesel.)
            date_of_birth -> Date,
            /// The `can_trade` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Bool`.
            ///
            /// (Automatically generated by Diesel.)
            can_trade -> Bool,
            /// The `user_id` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            user_id -> Uuid,
            /// The `created_at` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Nullable<Timestamptz>,
            /// The `updated_at` column of the `external.user_information` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Nullable<Timestamptz>,
        }
    }

    diesel::table! {
        /// Representation of the `external.users` table.
        ///
        /// (Automatically generated by Diesel.)
        external.users (id) {
            /// The `id` column of the `external.users` table.
            ///
            /// Its SQL type is `Uuid`.
            ///
            /// (Automatically generated by Diesel.)
            id -> Uuid,
            /// The `username` column of the `external.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 64]
            username -> Varchar,
            /// The `password` column of the `external.users` table.
            ///
            /// Its SQL type is `Varchar`.
            ///
            /// (Automatically generated by Diesel.)
            #[max_length = 255]
            password -> Varchar,
            /// The `is_active` column of the `external.users` table.
            ///
            /// Its SQL type is `Nullable<Bool>`.
            ///
            /// (Automatically generated by Diesel.)
            is_active -> Nullable<Bool>,
            /// The `created_at` column of the `external.users` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            created_at -> Nullable<Timestamptz>,
            /// The `updated_at` column of the `external.users` table.
            ///
            /// Its SQL type is `Nullable<Timestamptz>`.
            ///
            /// (Automatically generated by Diesel.)
            updated_at -> Nullable<Timestamptz>,
        }
    }

    diesel::joinable!(addresses -> users (user_id));
    diesel::joinable!(broker_information -> users (user_id));
    diesel::joinable!(trades -> trade_signals (signal_id));
    diesel::joinable!(trades -> users (user_id));
    diesel::joinable!(user_information -> users (user_id));

    diesel::allow_tables_to_appear_in_same_query!(
        addresses,
        broker_information,
        candles,
        trade_session,
        trade_signals,
        trades,
        user_information,
        users,
    );
}
